Feature/basic app
iam-Akshat/weather-app pull request #1
Opened 2021-03-26 19:14 UTC by iam-Akshat

- Use API to show weather data
- Use Async/Await to handle network requests

2021-03-27 02:42 UTC, wathigo requested changes
## CHANGES REQUIRED :o: 
Great job on this milestone.
Let's make a few changes before we move on.

### REQUIRED
* It uses Webpack ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/webpack_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/)).
* All webpack related packages should be included in `package.json` like `webpack`, `webpack-cli`, `webpack-dev-server` etc. Also, those packages should be added as **devDependencies** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/devdep_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/)).
* It changes its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app)).

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2021-03-27 02:42 UTC, wathigo commented on package.json
> +  },
**REQUIRED**
*  Necessary run common commands like build, development should be in package.json inside `scripts'. Here is a basic example ([screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/scripts_requirement.png)).
```json
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

2021-03-28 14:40 UTC, Torres-ssf requested changes
### Changes requried :muscle: 
Hi @iam-Akshat :hand: 
Awesome job on this project so far. But before moving on we need to make some changes.

- [ ] The page needs to have a toggle control to determine if the result will be shown in Celsius or Fahrenheit.
![Screenshot from 2021-03-28 11-25-22](https://user-images.githubusercontent.com/30977845/112755713-4e93de00-8fb8-11eb-8c9f-558fe3c0afa5.png)

- [x] Right now only the image shows the forecast (clear, rain...). It would be nice to also include a label to show it.


Happy coding :computer: 
**Sérgio Torres**

2021-03-28 17:32 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hello again @iam-Akshat :hand: 
We still need to work on the changes requested in the last review. Please let me know if the instructions were not clear, I will help you out :smiley: 

- [ ] Just like it's saying in the instructions, the page needs to have a toggle control to determine if the result will be shown in Celsius or Fahrenheit. So if the default temperature is represented in Celsius. clicking at the toggle you can change it to Fahrenheit. This convertion can be implemented using code, there is no need to do another request in the API.
![Screenshot from 2021-03-28 11-25-22](https://user-images.githubusercontent.com/30977845/112755713-4e93de00-8fb8-11eb-8c9f-558fe3c0afa5.png)

Happy coding :computer: 
**Sérgio Torres**

2021-03-28 20:15 UTC, Forison requested changes
#### Changes Required❌

# Hi @iam-Akshat, 

#### After cloning the branch and going through all the steps outline in the readme, below is I got😊
![Screenshot from 2021-03-28 16-10-53](https://user-images.githubusercontent.com/29695661/112766579-6e3efc80-8fe0-11eb-9dcb-47a12b8d6212.png)
I don't know if your attempt to address the earlier recommendation cause an error. Let us Address this and make sure all the earlier recommendation are addressed.😇

#### Kindly address the issue and submit a re-review🙂

#### Happy coding

Addo Forison

2021-03-28 21:05 UTC, Forison approved these changes
# Status::Approved✔️

# Good job, Readme point to the right direction, kindly proceed to the next task 😇.

#### Happy coding👨‍💻

Addo Forison

2021-03-28 21:37 UTC, merged